# Copyright 2025 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

[versions]
microej-sdk = "1.4.0"

[libraries]
# APIs
api-edc =                       { group = "ej.api", name = "edc", version = "1.3.5" }
api-event =                     { group = "ej.api", name = "event", version = "2.0.0" }

# Libraries
library-logging =               { group = "ej.library.eclasspath", name = "logging", version = "1.2.1" }
library-bytebuffer =            { group = "ej.library.eclasspath", name = "bytebuffer", version = "1.2.0" }

# Default VEE Port
veeport-nxp-mimxrt1170 =       { group = "com.nxp.vee.mimxrt1170", name = "vee-port", version = "3.1.0" }

# Mock libaries
mock-api =                      { group = "com.microej.tool.runtime", name = "mock-api", version = "2.6.0" }
